export const ROUTES = Object.freeze({
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/cadastro',
  STUDENT_REGISTER: '/cadastro/estudante',
  SELLER_REGISTER: '/cadastro/vendedor',
  PASSWORD_RECOVERY: '/recuperar-senha',
  STUDENT_HOME: '/estudante',
  SELLER_HOME: '/vendedor',
  SELLER_PROFILE: '/vendedor/perfil',
  SELLER_PRODUCTS: '/vendedor/produtos',
  SELLER_PRODUCT_NEW: '/vendedor/produtos/novo',
  SELLER_PRODUCT_EDIT: '/vendedor/produtos/:productId/editar',
  SELLER_MENUS: '/vendedor/cardapios',
  SELLER_MENU_NEW: '/vendedor/cardapios/novo',
  SELLER_ORDERS: '/vendedor/pedidos',
  SELLER_ORDER_DETAIL: '/vendedor/pedidos/:orderId',
  SELLER_HISTORY: '/vendedor/historico',
  ADMIN_HOME: '/admin',
  SELLERS: '/vendedores',
  CART: '/carrinho',
  PRODUCT: '/produto',
});
